$(function(){document.createElement('HEADER');document.createElement('VIDEO');var $win=$(window);var $doc=$(document);var $body=$('body');window.silex=window.silex||{};window.silex.scale=1;window.silex.scroll={top:0,left:0};window.silex.getCurrentPage=function(){var pageable=$body.pageable;var currentPageName=pageable?pageable().data()['silexlabs-pageable'].options.currentPage:$body.attr('data-current-page');var currentPage=window.silex.data.pages.filter(function(el){return el.id===currentPageName})[0];return currentPage;};window.silex.resizeBody=function(){};if(!$body.hasClass('silex-published')){var firstPageName=window.silex.data.pages[0].link.href;$body.on('pageChanged',function(event,pageName){$('[data-silex-href*="#!'+pageName+'"]').addClass('page-link-active');$('[data-silex-iframe-src]').each(function(){this.setAttribute('src',this.getAttribute('data-silex-iframe-src'));});$('.paged-element-hidden iframe').each(function(){var src=this.getAttribute('src');if(src){this.setAttribute('data-silex-iframe-src',src);this.setAttribute('src','');}});});$body.pageable({currentPage:firstPageName,useDeeplink:$body.hasClass('silex-runtime'),pageClass:'paged-element'});$('.silex-runtime [data-silex-href]').click(function(){var href=this.getAttribute('data-silex-href');if(href.indexOf('#')===0){window.location.href=href;}
else{window.open(href,'_blank');}});}
if(!$body.hasClass('silex-editor')){onScroll();onResize();$win.resize(onResize);$win.scroll(onScroll);}
function getScroll(){var container=$(document.scrollingElement||'html');return{left:container.scrollLeft(),top:container.scrollTop()}}
function onResize(){var ratio=getScaleRatio();var scroll=getScroll();$doc.trigger('silex.preresize');window.silex.scrollTop=scroll.top/ratio;window.silex.scrollLeft=scroll.left/ratio;window.silex.scale=ratio;if(ratio===1){$body.css({'transform':'','transform-origin':'','min-width':'','height':''});$('.prevent-scale').css({'transform':'','transform-origin':''})}
else{$body.css({'transform':'scale('+ratio+')','transform-origin':'0 0','min-width':getScaleBreakPoint()+'px','height':Math.round(window.innerHeight*ratio),});$('.prevent-scale').css({'transform':'scale('+(1/ratio)+')','transform-origin':'0 0'})}
$doc.trigger('silex.resize');}
function onScroll(){var ratio=getScaleRatio();var scroll=getScroll();$doc.trigger('silex.prescroll',{scrollTop:scroll.top/ratio,scrollLeft:scroll.left/ratio,scale:ratio});var offsetTop=scroll.top/ratio;var offsetLeft=scroll.left/ratio;window.silex.scrollTop=offsetTop;window.silex.scrollLeft=offsetLeft;window.silex.scale=ratio;$('.fixed').css({'transform':'translate('+offsetLeft+'px, '+offsetTop+'px)','transform-origin':'0 0'});$('.fixed.prevent-scale').css({'transform':'translate('+offsetLeft+'px, '+offsetTop+'px) scale('+(1/ratio)+')','transform-origin':'0 0'});$doc.trigger('silex.scroll');}
function isBellowBreakPoint(){return window.matchMedia('only screen and (max-width: 480px)').matches;}
function getScaleRatio(){var winWidth=$win.width();if((window.silex.data.site.width&&winWidth<window.silex.data.site.width)||isBellowBreakPoint()){var breakPoint=getScaleBreakPoint();return winWidth/breakPoint;}
return 1;}
function getScaleBreakPoint(){return isBellowBreakPoint()?480:window.silex.data.site.width;}});